In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [24]:
data['EstimatedSalary'].mean()

100090.239881

In [6]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\harsh\OneDrive\Desktop\ANN Clasification Project\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [13]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From c:\Users\harsh\OneDrive\Desktop\ANN Clasification Project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\harsh\OneDrive\Desktop\ANN Clasification Project\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\harsh\OneDrive\Desktop\ANN Clasification Project\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\harsh\OneDrive\Desktop\ANN Clasification Project\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 2ms/step - loss: 100371.7109 - mae: 100371.7109 - val_loss: 98497.6172 - val_mae: 98497.6172
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 99572.1328 - mae: 99572.1328 - val_loss: 96901.6875 - val_mae: 96901.6875
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 96820.6953 - mae: 96820.6953 - val_loss: 92891.1016 - val_mae: 92891.1016
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 91475.7422 - mae: 91475.7422 - val_loss: 86273.4297 - val_mae: 86273.4297
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 83707.3047 - mae: 83707.3047 - val_loss: 77703.4609 - val_mae: 77703.4609
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 74602.2656 - mae: 74602.2656 - val_loss: 68900.3438 - val_mae: 68900.3438
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 65910.3047 - mae: 65910.3047 - val_loss: 61416.9336 - val_mae: 61416.9336
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 58960.0781 - mae: 58960.0781 - val_loss: 55980.6602 - val_mae: 55980.6602
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 54503.7617 - mae: 54503.7617 - val_loss: 52814.8750 - val_mae: 52814.8750
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 52113.9883 - mae: 52113.9883 - val_loss: 51493.2383 - val_mae: 51493.2383
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 51073.2305 - mae: 51073.2305 - val_loss: 51014.5117 - val_mae: 51014.5117
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 50632.3750 - mae: 50632.3750 - val_loss: 50823.7227 - val_mae: 50823.7227
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 50449.8789 - mae: 50449.8789 - val_loss: 50745.6875 - val_mae: 50745.6875
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 50344.7734 - mae: 50344.7734 - val_loss: 50682.3203 - val_mae: 50682.3203
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 50270.8125 - mae: 50270.8125 - val_loss: 50629.5117 - val_mae: 50629.5117
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 50210.5195 - mae: 50210.5195 - val_loss: 50589.0938 - val_mae: 50589.0938
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 50161.7070 - mae: 50161.7070 - val_loss: 50546.5234 - val_mae: 50546.5234
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 50118.2656 - mae: 50118.2656 - val_loss: 50501.0742 - val_mae: 50501.0742
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 50076.0703 - mae: 50076.0703 - val_loss: 50459.2773 - val_mae: 50459.2773
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 50040.7578 - mae: 50040.7578 - val_loss: 50444.5469 - val_mae: 50444.5469
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 50007.1562 - mae: 50007.1562 - val_loss: 50409.0938 - val_mae: 50409.0938
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 49975.2734 - mae: 49975.2734 - val_loss: 50391.3281 - val_mae: 50391.3281
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 49949.7070 - mae: 49949.7070 - val_loss: 50369.3125 - val_mae: 50369.3125
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 49919.9375 - mae: 49919.9375 - val_loss: 50343.0938 - val_mae: 50343.0938
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 49898.4688 - mae: 49898.4688 - val_loss: 50320.6758 - val_mae: 50320.6758
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 49870.1094 - mae: 49870.1094 - val_loss: 50307.6992 - val_mae: 50307.6992
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 49846.1328 - mae: 49846.1328 - val_loss: 50285.1250 - val_mae: 50285.1250
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 49822.0742 - mae: 49822.0742 - val_loss: 50270.9922 - val_mae: 50270.9922
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: 49802.5430 - mae: 49802.5430 - val_loss: 50261.5156 - val_mae: 50261.5156
Epoch 30/100
250/250 [==============================] - 0s 1ms/step - loss: 49782.1406 - mae: 49782.1406 - val_loss: 50248.0938 - val_mae: 50248.0938
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 49761.2656 - mae: 49761.2656 - val_loss: 50230.8320 - val_mae: 50230.8320
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 49745.2773 - mae: 49745.2773 - val_loss: 50229.3672 - val_mae: 50229.3672
Epoch 33/100
250/250 [==============================] - 0s 1ms/step - loss: 49728.1406 - mae: 49728.1406 - val_loss: 50213.6875 - val_mae: 50213.6875
Epoch 34/100
250/250 [==============================] - 0s 1ms/step - loss: 49711.7031 - mae: 49711.7031 - val_loss: 50202.3438 - val_mae: 50202.3438
Epoch 35/100
250/250 [==============================] - 0s 1ms/step - loss: 49692.7812 - mae: 49692.7812 - val_loss: 50205.1562 - val_mae: 50205.1562
Epoch 36/100
250/250 [==============================] - 0s 1ms/step - loss: 49680.7188 - mae: 49680.7188 - val_loss: 50202.2305 - val_mae: 50202.2305
Epoch 37/100
250/250 [==============================] - 0s 1ms/step - loss: 49668.3438 - mae: 49668.3438 - val_loss: 50195.3672 - val_mae: 50195.3672
Epoch 38/100
250/250 [==============================] - 0s 1ms/step - loss: 49651.4766 - mae: 49651.4766 - val_loss: 50184.9844 - val_mae: 50184.9844
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: 49638.0078 - mae: 49638.0078 - val_loss: 50187.4023 - val_mae: 50187.4023
Epoch 40/100
250/250 [==============================] - 0s 1ms/step - loss: 49626.5977 - mae: 49626.5977 - val_loss: 50186.7188 - val_mae: 50186.7188
Epoch 41/100
250/250 [==============================] - 0s 1ms/step - loss: 49615.6250 - mae: 49615.6250 - val_loss: 50185.3633 - val_mae: 50185.3633
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 49602.7344 - mae: 49602.7344 - val_loss: 50181.2266 - val_mae: 50181.2266
Epoch 43/100
250/250 [==============================] - 0s 1ms/step - loss: 49593.4609 - mae: 49593.4609 - val_loss: 50186.8828 - val_mae: 50186.8828
Epoch 44/100
250/250 [==============================] - 0s 1ms/step - loss: 49583.4609 - mae: 49583.4609 - val_loss: 50169.4609 - val_mae: 50169.4609
Epoch 45/100
250/250 [==============================] - 0s 1ms/step - loss: 49572.0156 - mae: 49572.0156 - val_loss: 50162.3750 - val_mae: 50162.3750
Epoch 46/100
250/250 [==============================] - 0s 1ms/step - loss: 49561.7227 - mae: 49561.7227 - val_loss: 50158.4883 - val_mae: 50158.4883
Epoch 47/100
250/250 [==============================] - 0s 1ms/step - loss: 49555.6445 - mae: 49555.6445 - val_loss: 50160.8555 - val_mae: 50160.8555
Epoch 48/100
250/250 [==============================] - 0s 1ms/step - loss: 49547.4727 - mae: 49547.4727 - val_loss: 50160.4023 - val_mae: 50160.4023
Epoch 49/100
250/250 [==============================] - 0s 1ms/step - loss: 49538.3711 - mae: 49538.3711 - val_loss: 50159.0469 - val_mae: 50159.0469
Epoch 50/100
250/250 [==============================] - 0s 1ms/step - loss: 49530.1562 - mae: 49530.1562 - val_loss: 50158.9805 - val_mae: 50158.9805
Epoch 51/100
250/250 [==============================] - 0s 1ms/step - loss: 49526.9219 - mae: 49526.9219 - val_loss: 50156.4648 - val_mae: 50156.4648
Epoch 52/100
250/250 [==============================] - 0s 1ms/step - loss: 49516.2695 - mae: 49516.2695 - val_loss: 50150.1680 - val_mae: 50150.1680
Epoch 53/100
250/250 [==============================] - 0s 1ms/step - loss: 49509.5625 - mae: 49509.5625 - val_loss: 50152.0391 - val_mae: 50152.0391
Epoch 54/100
250/250 [==============================] - 0s 1ms/step - loss: 49501.5352 - mae: 49501.5352 - val_loss: 50148.0195 - val_mae: 50148.0195
Epoch 55/100
250/250 [==============================] - 0s 1ms/step - loss: 49495.4766 - mae: 49495.4766 - val_loss: 50157.7812 - val_mae: 50157.7812
Epoch 56/100
250/250 [==============================] - 0s 1ms/step - loss: 49487.4023 - mae: 49487.4023 - val_loss: 50150.0781 - val_mae: 50150.0781
Epoch 57/100
250/250 [==============================] - 0s 1ms/step - loss: 49484.7891 - mae: 49484.7891 - val_loss: 50148.5703 - val_mae: 50148.5703
Epoch 58/100
250/250 [==============================] - 0s 1ms/step - loss: 49478.6875 - mae: 49478.6875 - val_loss: 50154.3242 - val_mae: 50154.3242
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 49469.0898 - mae: 49469.0898 - val_loss: 50157.5938 - val_mae: 50157.5938
Epoch 60/100
250/250 [==============================] - 0s 1ms/step - loss: 49464.5781 - mae: 49464.5781 - val_loss: 50153.2305 - val_mae: 50153.2305
Epoch 61/100
250/250 [==============================] - 0s 1ms/step - loss: 49457.0586 - mae: 49457.0586 - val_loss: 50141.9688 - val_mae: 50141.9688
Epoch 62/100
250/250 [==============================] - 0s 1ms/step - loss: 49451.3828 - mae: 49451.3828 - val_loss: 50147.6289 - val_mae: 50147.6289
Epoch 63/100
250/250 [==============================] - 0s 1ms/step - loss: 49445.5117 - mae: 49445.5117 - val_loss: 50144.4844 - val_mae: 50144.4844
Epoch 64/100
250/250 [==============================] - 0s 1ms/step - loss: 49444.9805 - mae: 49444.9805 - val_loss: 50135.1484 - val_mae: 50135.1484
Epoch 65/100
250/250 [==============================] - 0s 1ms/step - loss: 49439.8906 - mae: 49439.8906 - val_loss: 50137.6953 - val_mae: 50137.6953
Epoch 66/100
250/250 [==============================] - 0s 1ms/step - loss: 49435.4023 - mae: 49435.4023 - val_loss: 50150.8594 - val_mae: 50150.8594
Epoch 67/100
250/250 [==============================] - 0s 1ms/step - loss: 49430.1875 - mae: 49430.1875 - val_loss: 50142.4219 - val_mae: 50142.4219
Epoch 68/100
250/250 [==============================] - 0s 1ms/step - loss: 49424.5586 - mae: 49424.5586 - val_loss: 50147.9102 - val_mae: 50147.9102
Epoch 69/100
250/250 [==============================] - 0s 1ms/step - loss: 49420.6523 - mae: 49420.6523 - val_loss: 50156.0898 - val_mae: 50156.0898
Epoch 70/100
250/250 [==============================] - 0s 1ms/step - loss: 49414.5938 - mae: 49414.5938 - val_loss: 50154.7773 - val_mae: 50154.7773
Epoch 71/100
250/250 [==============================] - 0s 1ms/step - loss: 49412.9570 - mae: 49412.9570 - val_loss: 50154.1484 - val_mae: 50154.1484
Epoch 72/100
250/250 [==============================] - 0s 1ms/step - loss: 49409.9844 - mae: 49409.9844 - val_loss: 50155.9492 - val_mae: 50155.9492
Epoch 73/100
250/250 [==============================] - 0s 1ms/step - loss: 49401.7539 - mae: 49401.7539 - val_loss: 50153.8281 - val_mae: 50153.8281
Epoch 74/100
250/250 [==============================] - 0s 1ms/step - loss: 49402.7070 - mae: 49402.7070 - val_loss: 50163.6562 - val_mae: 50163.6562

In [17]:
%load_ext tensorboard

In [18]:
%tensorboard --logdir regressionlogs/fit

In [19]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 702us/step - loss: 50135.1484 - mae: 50135.1484
Test MAE : 50135.1484375

In [20]:
model.save('regression_model.h5')

c:\Users\harsh\OneDrive\Desktop\ANN Clasification Project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(